xfz/apps/cms/urls.py
from django.urls import path
from . import views, course_view, staff_views

app_name = "cms"

urlpatterns = [
    path('', views.index, name="index"),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
    path("write_news/", views.WriteNewsView.as_view(), name="write_news"),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
    path("news_category/", views.news_category, name="news_category"),
    path("add_news_category/", views.add_news_category, name="add_news_category"),
    path("edit_news_category/", views.edit_news_category, name="edit_news_category"),
    path("delete_news_category/", views.delete_news_category, name="delete_news_category"),
    path("banners/", views.banners, name="banners"),
    path("add_banner/", views.add_banner, name="add_banner"),
    path("banner_list/", views.banner_list, name="banner_list"),
    path("delete_banner/", views.delete_banner, name="delete_banner"),
    path("edit_banner/", views.edit_banner, name="edit_banner"),
    path("upload_file/", views.upload_file, name="upload_file"),
    path("qntoken/", views.qntoken, name="qntoken"),
    path("pay_info/", views.PayInfoView.as_view(), name="pay_info"),
    path("payinfo_list/", views.PayInfoListView.as_view(), name="payinfo_list"),
    path("edit_payinfo/", views.EditPayInfoView.as_view(), name="edit_payinfo"),
    path("delete_payinfo/", views.delete_payinfo, name="delete_payinfo"),
]

urlpatterns += [
    path('pub_course/', course_view.PubCourse.as_view(), name="pub_course"),
    path('course_category/', course_view.course_category, name="course_category"),
    path('add_course_category/', course_view.add_course_category, name="add_course_category"),
    path("edit_course_category/", course_view.edit_course_category, name="edit_course_category"),
    path("delete_course_category/", course_view.delete_course_category, name="delete_course_category"),
    path('course_list/', course_view.CourseListView.as_view(), name='course_list'),
    path("edit_course/", course_view.EditCourseView.as_view(), name='edit_course'),
    path("delete_course/", course_view.delete_course, name="delete_course")
]

# 员工管理
urlpatterns += [
    path('staffs/', staff_views.staffs_view, name='staffs'),
    path('add_staff/', staff_views.AddStaffView.as_view(), name='add_staff'),
    path('delete_staff/', staff_views.delete_staff, name='delete_staff'),
]

xfz/apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_index, name='course_index'),
    path('<int:course_id>/', views.course_detail, name='course_detail'),
    path('course_token/', views.course_token, name='course_token'),
    path('course_order/<int:course_id>/', views.course_order, name='course_order'),
    path('course_order_key/', views.course_order_key, name="course_order_key"),
    path('notify_view/', views.notify_view, name='notify_view')
]

xfz/apps/news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path('<int:news_id>/', views.news_detail, name="news_detail"),
    path('list/', views.news_list, name='news_list'),
    path('public_comment/', views.public_comment, name='public_comment')
]

xfz/apps/payinfo/urls.py
from django.urls import path
from . import views

app_name = "payinfo"

urlpatterns = [
    path('', views.index, name='index'),
    path('payinfo_order/', views.payinfo_order, name='payinfo_order'),
    path('notify_url/', views.notify_view, name='notify_view'),
    path('download/', views.download, name='download')
]

xfz/xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', views.index, name='index'),
                  path('search/', include('haystack.urls')),
                  path('cms/', include('apps.cms.urls')),
                  path('account/', include("apps.xfzauth.urls")),
                  path('news/', include('apps.news.urls')),
                  path("course/", include("apps.course.urls")),
                  path("payinfo/", include("apps.payinfo.urls")),
                  path("ueditor/", include("apps.ueditor.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

xfz/apps/cms/models.py
from django.db import models

xfz/apps/course/models.py
# encoding: utf-8

from django.db import models
from shortuuidfield import ShortUUIDField


class CourseCategory(models.Model):
    name = models.CharField(max_length=100)


class Teacher(models.Model):
    username = models.CharField(max_length=100)
    avatar = models.URLField()
    jobtitle = models.CharField(max_length=100)
    profile = models.TextField()


class Course(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey('CourseCategory', on_delete=models.DO_NOTHING)
    teacher = models.ForeignKey("Teacher", on_delete=models.DO_NOTHING)
    video_url = models.URLField()
    cover_url = models.URLField()
    price = models.FloatField()
    duration = models.IntegerField()
    profile = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)


class CourseOrder(models.Model):
    uid = ShortUUIDField(primary_key=True)
    course = models.ForeignKey("Course", on_delete=models.DO_NOTHING)
    buyer = models.ForeignKey("xfzauth.User", on_delete=models.DO_NOTHING)
    amount = models.FloatField(default=0)
    pub_time = models.DateTimeField(auto_now_add=True)
    # 1：代表的是支付宝支付。2：代表的是微信支付
    istype = models.SmallIntegerField(default=0)
    # 1：代表的是未支付。2：代表的是支付成功
    status = models.SmallIntegerField(default=1)

xfz/apps/news/models.py
from django.db import models


class NewsCategory(models.Model):
    name = models.CharField(max_length=100)


class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('NewsCategory', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('xfzauth.User', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-pub_time']


class Comment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey("News", on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey("xfzauth.User", on_delete=models.CASCADE)

    class Meta:
        ordering = ['-pub_time']


class Banner(models.Model):
    priority = models.IntegerField(default=0)
    image_url = models.URLField()
    link_to = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-priority']

xfz/apps/payinfo/models.py
from django.db import models
from shortuuidfield import ShortUUIDField
from django.core import validators
from django.conf import settings


class Payinfo(models.Model):
    title = models.CharField(max_length=100)
    profile = models.CharField(max_length=200)
    price = models.FloatField()
    path = models.FilePathField()


class PayinfoOrder(models.Model):
    uid = ShortUUIDField(primary_key=True)
    payinfo = models.ForeignKey("Payinfo", on_delete=models.DO_NOTHING)
    buyer = models.ForeignKey("xfzauth.User", on_delete=models.DO_NOTHING)
    amount = models.FloatField(default=0)
    pub_time = models.DateTimeField(auto_now_add=True)
    # 1：代表的是支付宝支付。2：代表的是微信支付
    istype = models.SmallIntegerField(default=0)
    # 1：代表的是未支付。2：代表的是支付成功
    status = models.SmallIntegerField(default=1)

xfz/apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import View
from django.views.decorators.http import require_POST, require_GET
from ..news.models import NewsCategory, News, Banner
from ..course.models import Course, CourseCategory
from ..payinfo.models import Payinfo, PayinfoOrder
from ..utils import restful
from .forms import EditNewsCategoryForm, WriteNewsForm, AddBannerForm, EditBannerForm, EditNewsForm, PubCourseForm, \
    PayInfoForm
import os
from django.conf import settings
import qiniu
from ..news.serializers import BannerSerializer
from datetime import datetime
from django.utils.timezone import make_aware
from django.core.paginator import Paginator
from urllib import parse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required


# 发布资讯
@method_decorator(permission_required(perm="payinfo.add_payinfo", login_url='/'), name='dispatch')
class PayInfoView(View):
    def get(self, request):
        payinfo = Payinfo.objects.all()
        context = {
            'payinfo': payinfo
        }
        return render(request, 'cms/pay_info.html', context=context)

    def post(self, request):
        title = request.POST.get("title")
        profile = request.POST.get("profile")
        path = request.POST.get("path")
        price = request.POST.get("price")

        print("=========================")
        # form = PayInfoForm(request.POST)
        # if form.is_valid():
        # title = form.cleaned_data.get("title")
        print(title)
        # profile = form.cleaned_data.get("profile")
        print(profile)

        # path = form.cleaned_data.get("path")
        print(path)
        print("===========path============")
        # price = form.cleaned_data.get("price")
        Payinfo.objects.create(title=title, profile=profile, path=path, price=price)
        return restful.ok()
        # else:
        #     Payinfo.objects.create(title=title, profile=profile, path=path, price=price)
        #     return restful.ok()

        # return restful.params_error(message=form.get_errors())


@method_decorator(permission_required(perm="payinfo.change_payinfo", login_url='/'), name='dispatch')
class PayInfoListView(View):
    def get(self, request):
        # request.GET：获取出来的所有数据，都是字符串类型
        page = int(request.GET.get('p', 1))
        title = request.GET.get('title')
        profile = request.GET.get('profile')
        # request.GET.get(参数,默认值)
        # 这个默认值是只有这个参数没有传递的时候才会使用
        # 如果传递了，但是是一个空的字符串，那么也不会使用默认值

        payinfoes = Payinfo.objects.all()

        if title:
            payinfoes = payinfoes.filter(title__icontains=title)

        if profile:
            payinfoes = payinfoes.filter(profile__icontains=profile)

        paginator = Paginator(payinfoes, 4)
        page_obj = paginator.page(page)

        context_data = self.get_pagination_data(paginator, page_obj)

        context = {
            'payinfoes': page_obj.object_list,
            'page_obj': page_obj,
            'paginator': paginator,

            'title': title,
            'profile': profile,

            'url_query': '&' + parse.urlencode({

                'profile': profile or '',
                'title': title or '',

            })
        }

        context.update(context_data)
        return render(request, 'cms/payinfo_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_count, current_page)

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page + 1, num_pages + 1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_count + 1)

        return {
            # left_pages：代表的是当前这页的左边的页的页码
            'left_pages': left_pages,
            # right_pages：代表的是当前这页的右边的页的页码
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': num_pages
        }


@method_decorator(permission_required(perm="payinfo.change_payinfo", login_url='/'), name='dispatch')
class EditPayInfoView(View):
    def get(self, request):
        payinfo_id = request.GET.get('payinfo_id')
        payinfo = Payinfo.objects.get(pk=payinfo_id)
        context = {
            'payinfo': payinfo,
        }
        return render(request, 'cms/pay_info.html', context=context)

    def post(self, request):
        title = request.POST.get("title")
        profile = request.POST.get("profile")
        path = request.POST.get("path")
        price = request.POST.get("price")
        pk = request.POST.get("pk")

        Payinfo.objects.filter(pk=pk).update(title=title, profile=profile, path=path, price=price)
        return restful.ok()


@require_POST
@permission_required(perm="payinfo.delete_payinfo", login_url='/')
def delete_payinfo(request):
    payinfo_id = request.POST.get('payinfo_id')
    Payinfo.objects.filter(pk=payinfo_id).delete()
    return restful.ok()


# 没有访问权力的直接重定向到首页
@staff_member_required(login_url="index")
def index(request):
    return render(request, 'cms/index.html')


# 发布新闻页面
@method_decorator(permission_required(perm="news.add_news", login_url='/'), name='dispatch')
class WriteNewsView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get("title")
            desc = form.cleaned_data.get("desc")
            thumbnail = form.cleaned_data.get("thumbnail")
            content = form.cleaned_data.get("content")
            category_id = form.cleaned_data.get("category")
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.create(title=title, desc=desc, thumbnail=thumbnail, content=content, category=category,
                                author=request.user)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


# 新闻分类
@require_GET
@permission_required(perm="news.add_newscategory", login_url='/')
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'cms/news_category.html', context=context)


# 添加新闻分类
@require_POST
@permission_required(perm="news.add_newscategory", login_url='/')
def add_news_category(request):
    name = request.POST.get("name")
    # 判断分类是否存在
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        # 添加
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message="该分类已经存在！")


# 编辑新闻分类
@require_POST
@permission_required(perm="news.change_newscategory", login_url='/')
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get("pk")
        name = form.cleaned_data.get("name")
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message="该分类不存在")
    else:
        return restful.params_error(message=form.get_error())


# 删除分类
@require_POST
@permission_required(perm="news.delete_newscategory", login_url='/')
def delete_news_category(request):
    pk = request.POST.get("pk")
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.unauth(message='该分类不存在！')


# 上传图片
@require_POST
@staff_member_required(login_url='index')
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    # http://127.0.0.1:8000/media/abc.jpg
    return restful.result(data={'url': url})


@require_GET
@staff_member_required(login_url='index')
def qntoken(request):
    access_key = settings.QINIU_ACCESS_KEY
    secret_key = settings.QINIU_SECRET_KEY

    bucket = settings.QINIU_BUCKET_NAME
    q = qiniu.Auth(access_key, secret_key)
    token = q.upload_token(bucket)
    return restful.result(data={"token": token})


@permission_required(perm="news.add_banner", login_url='/')
def banners(request):
    return render(request, 'cms/banners.html')


@permission_required(perm="news.add_banner", login_url='/')
def add_banner(request):
    form = AddBannerForm(request.POST)
    if form.is_valid():
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')
        link_to = form.cleaned_data.get('link_to')
        banner = Banner.objects.create(priority=priority, image_url=image_url, link_to=link_to)
        return restful.result(data={"banner_id": banner.pk})
    else:
        return restful.params_error(message=form.get_errors())


@permission_required(perm="news.add_banner", login_url='/')
def banner_list(request):
    banners = Banner.objects.all()
    serialize = BannerSerializer(banners, many=True)
    return restful.result(data=serialize.data)


@permission_required(perm="news.delete_banner",login_url='/')
def delete_banner(request):

xfz/front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 小饭桌管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">小饭桌后台管理系统</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="http://edu-image.nosdn.127.net/4B9BE586B1F982317B930C2C2E6F702D.png"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">{{ user.username }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="http://edu-image.nosdn.127.net/4B9BE586B1F982317B930C2C2E6F702D.png"
                                     class="img-circle" alt="User Image">
                                <p>
                                    {{ user.username }}
                                    <small>Python web开发工程师</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="首页">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
          </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                {% if perms.news.change_news %}
                <li class="header">新闻管理</li>
                <li>
                    <a href="{% url 'cms:news_list' %}">
                        <i class="fa fa-list"></i>
                        <span>新闻列表</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'cms:write_news' %}">
                        <i class="fa fa-edit"></i>
                        <span>发布新闻</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'cms:news_category' %}">
                        <i class="fa fa-tag"></i>
                        <span>新闻分类</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'cms:banners' %}">
                        <i class="fa fa-window-restore"></i>
                        <span>轮播图</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.course.change_course %}
                <li class="header">课程管理</li>
                <li>
                    <a href="{% url 'cms:pub_course' %}">
                        <i class="fa fa-tv"></i>
                        <span>发布课程</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'cms:course_category' %}">
                        <i class="fa fa-tv"></i>
                        <span>课程分类</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'cms:course_list' %}">
                        <i class="fa fa-tv"></i>
                        <span>课程列表</span>
                    </a>
                </li>
                {% endif %}
                {% if perms.payinfo.change_payinfo %}
                <li class="header">资讯管理</li>
                <li>
                    <a href="{% url 'cms:pay_info' %}">
                        <i class="fa fa-edit"></i>
                        <span>发表资讯</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'cms:payinfo_list' %}">
                        <i class="fa fa-edit"></i>
                        <span>资讯列表</span>
                    </a>
                </li>
                {% endif %}
                {% if user.is_superuser %}
                <li class="header">员工管理</li>
                <li>
                    <a href="{% url 'cms:staffs' %}">
                        <i class="fa fa-group"></i>
                        <span>员工管理</span>
                    </a>
                </li>
                {% endif %}

            </ul>
        </section>
    </aside>
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>
        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>
    <footer class="main-footer">
        <strong>小饭桌</strong>后台管理系统
    </footer>
</div>
</body>
</html>

xfz/front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首页{% endblock %}

{% block content-header %}
    <h1>欢迎来到小饭桌CMS管理系统</h1>
{% endblock %}

xfz/front/templates/cms/payinfo_list.html
{% extends 'cms/base.html' %}


{% block title %}
新闻列表
{% endblock %}

{% block head %}
<style>
    .left-group{
        margin-right: 20px;
    }
</style>
<link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
<script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
<script src="{% static 'js/payinfo_list.min.js' %}"></script>
{% endblock %}

{% block content-header %}
<h1>资讯列表管理</h1>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <form action="" method="get" class="form-inline">
                    <div class="form-group left-group">
                        <label for="title-input">标题：</label>
                        {% if title %}
                        <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字" value="{{ title }}">
                        {% else %}
                        <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字">
                        {% endif %}
                    </div>

                    <div class="form-group left-group">
                        <button class="btn btn-primary">查询</button>
                    </div>
                    <div class="form-group">
                        <a href="{% url 'cms:payinfo_list' %}">清除查询</a>
                    </div>
                </form>
            </div>
            <div class="box-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>标题</th>
                        <th>描述</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for payinfo in payinfoes %}
                    <tr>
                        <td><a target="_blank" href="{% url 'cms:payinfo_list' %}">{{ payinfo.title }}</a></td>
                        <td>{{ payinfo.profile }}</td>


                        <td>
                            <a href="{% url 'cms:edit_payinfo' %}?payinfo_id={{ payinfo.pk }}" class="btn btn-info btn-xs">编辑</a>
                            <button class="btn btn-danger btn-xs delete-btn" data-payinfo-id="{{ payinfo.pk }}">删除</button>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="box-footer">
                <p class="pull-left">第{{ current_page }}/总共{{ num_pages }}页</p>
                <ul class="pagination pull-right">
                    {#上一页#}
                    {% if page_obj.has_previous %}
                    <li><a href="?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                    {% else %}
                    <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                    {% endif %}

                    {# 是否需要出现三个点 #}
                    {% if left_has_more %}
                    <li><a href="?p=1">1</a></li>
                    <li><a href="javascript:void(0);">...</a></li>
                    {% endif %}

                    {# 左边的页码 #}
                    {% for left_page in left_pages %}
                    <li><a href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                    {% endfor %}

                    {# 当前的页面 #}
                    <li class="active"><a href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                    {# 右边的页码 #}
                    {% for right_page in right_pages %}
                    <li><a href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                    {% endfor %}

                    {# 用来控制右边三个点 #}
                    {% if right_has_more %}
                    <li><a href="javascript:void(0);">...</a></li>
                    <li><a href="?p={{ num_pages }}{{ url_query }}">{{ num_pages }}</a></li>
                    {% endif %}

                    {#下一页#}
                    {% if page_obj.has_next %}
                    <li><a href="?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                    {% else %}
                    <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

400 700 3030
400 699 3030