xfz/apps/cms/urls.py
from django.urls import path
from . import views, course_view, staff_views

app_name = "cms"

urlpatterns = [
    path('', views.index, name="index"),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
    path("write_news/", views.WriteNewsView.as_view(), name="write_news"),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
    path("news_category/", views.news_category, name="news_category"),
    path("add_news_category/", views.add_news_category, name="add_news_category"),
    path("edit_news_category/", views.edit_news_category, name="edit_news_category"),
    path("delete_news_category/", views.delete_news_category, name="delete_news_category"),
    path("banners/", views.banners, name="banners"),
    path("add_banner/", views.add_banner, name="add_banner"),
    path("banner_list/", views.banner_list, name="banner_list"),
    path("delete_banner/", views.delete_banner, name="delete_banner"),
    path("edit_banner/", views.edit_banner, name="edit_banner"),
    path("upload_file/", views.upload_file, name="upload_file"),
    path("qntoken/", views.qntoken, name="qntoken"),
    path("pay_info/", views.PayInfoView.as_view(), name="pay_info"),
    path("payinfo_list/", views.PayInfoListView.as_view(), name="payinfo_list"),
    path("edit_payinfo/", views.EditPayInfoView.as_view(), name="edit_payinfo"),
    path("delete_payinfo/", views.delete_payinfo, name="delete_payinfo"),
]

urlpatterns += [
    path('pub_course/', course_view.PubCourse.as_view(), name="pub_course"),
    path('course_category/', course_view.course_category, name="course_category"),
    path('add_course_category/', course_view.add_course_category, name="add_course_category"),
    path("edit_course_category/", course_view.edit_course_category, name="edit_course_category"),
    path("delete_course_category/", course_view.delete_course_category, name="delete_course_category"),
    path('course_list/', course_view.CourseListView.as_view(), name='course_list'),
    path("edit_course/", course_view.EditCourseView.as_view(), name='edit_course'),
    path("delete_course/", course_view.delete_course, name="delete_course")
]

# 员工管理
urlpatterns += [
    path('staffs/', staff_views.staffs_view, name='staffs'),
    path('add_staff/', staff_views.AddStaffView.as_view(), name='add_staff'),
    path('delete_staff/', staff_views.delete_staff, name='delete_staff'),
]

xfz/apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_index, name='course_index'),
    path('<int:course_id>/', views.course_detail, name='course_detail'),
    path('course_token/', views.course_token, name='course_token'),
    path('course_order/<int:course_id>/', views.course_order, name='course_order'),
    path('course_order_key/', views.course_order_key, name="course_order_key"),
    path('notify_view/', views.notify_view, name='notify_view')
]

xfz/apps/payinfo/urls.py
from django.urls import path
from . import views

app_name = "payinfo"

urlpatterns = [
    path('', views.index, name='index'),
    path('payinfo_order/', views.payinfo_order, name='payinfo_order'),
    path('notify_url/', views.notify_view, name='notify_view'),
    path('download/', views.download, name='download')
]

xfz/apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path("img_captcha/", views.img_captcha, name='img_captcha'),
    path('cache_test/', views.cache_test, name='cache_test'),
    path("sms_captcha/", views.sms_captcha, name="sms_captcha"),
    path('register/', views.register, name='register'),

]

xfz/xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', views.index, name='index'),
                  path('search/', include('haystack.urls')),
                  path('cms/', include('apps.cms.urls')),
                  path('account/', include("apps.xfzauth.urls")),
                  path('news/', include('apps.news.urls')),
                  path("course/", include("apps.course.urls")),
                  path("payinfo/", include("apps.payinfo.urls")),
                  path("ueditor/", include("apps.ueditor.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

xfz/front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1605443_l58arb13mu.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1605443_0viuzxuci6ue.css">
    <link rel="stylesheet" href="{% static 'css/common/auth.min.css' %}">
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/front_base.min.js' %}"></script>


    {% block head %} {% endblock %}

</head>
<body>
<header class="header">
    <div class="container">

        <div class="logo-box">
            <a href="/"></a>
        </div>

        <ul class="nav">
            <li class="active"><a href="/">创业资讯</a></li>
            <li><a href="{% url 'course:course_index' %}">创业课堂</a></li>
            <li><a href="{% url 'payinfo:index' %}">付费资讯</a></li>
            <li><a href="/search/">搜索</a></li>
        </ul>

        <div class="auth-box">
            <i class="icon-person iconperson iconfont"></i>
            {% if user.is_authenticated %}
                <a href="#" class="authenticated-box">{{ user.username }}</a>
                <div class="user-more-box">
                    <i class="triangle"></i>
                    {% if user.is_staff %}
                        <a href="{% url 'cms:index' %}">管理系统</a>
                    {% endif %}
                        <a href="{% url 'xfzauth:logout' %}">退出登录</a>
                </div>
            {% else %}
                <a href="#" class="signin-btn">登录</a> /
                <a href="#" class="signup-btn">注册</a>
            {% endif %}
        </div>
    </div>
</header>
{% block main %} {% endblock %}
<footer class="footer">
    <div class="top-group">
        <div class="top-inner-group">
            <div class="logo-box"></div>
            <div class="detail-group">
                <div class="line1">
                    <ul class="links">
                        <li><a href="#">小饭桌</a></li>
                        <li><a href="#">创业课堂</a></li>
                        <li><a href="#">寻求报道</a></li>
                        <li><a href="#">创业礼包</a></li>
                    </ul>
                    <div class="about-us">
                        <span class="title">关于我们：</span>
                        <ul class="social-group">
                            <li class="weixin">
                                <div class="wx-qrcode"></div>
                                <span class="text">xfz008</span>
                            </li>
                            <li class="weibo">
                                <a class="text" href="#">小饭桌创业课堂</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="line2">
                    <p class="address">北京市朝阳区东三环北路38号院泰康金融大厦</p>
                    <p class="contact">电话：17765602533</p>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom-group">
        @2019北京木子投资顾问有限公司
    </div>
</footer>
<div class="mask-wrapper">
    <div class="auth-wrapper">
        <div class="close-wrapper">
            <span class="close-btn iconguanbi iconfont"></span>
        </div>
        <div class="auth-inner-wrapper">
            <div class="scroll-wrapper">
                <div class="signin-group auth-group">
                    <div class="top-group">
                        <span class="title">请登录</span>
                        <a href="javascript: void(0);" class="switch">立即注册></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password" placeholder="请输入密码">
                        </div>
                        <div class="input-group">
                            <label class="remember-label">
                                <input type="checkbox" name="remember" value="1">
                                记住我
                            </label>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" value="立即登录">
                        </div>
                    </div>
                </div>
                <div class="signup-group auth-group">
                    <div class="top-group">
                        <span class="title">请注册</span>
                        <a href="javascript: void(0);" class="switch">立即登录></a>
                    </div>
                    <div class="form-group">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control" name="username" placeholder="用户名">
                        </div>
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                            </div>
                            <div class="input-group-addon" >
                                <img src="{% url 'xfzauth:img_captcha' %}" alt="" class="img-captcha" style="cursor:pointer">
                            </div>
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password1" placeholder="密码">
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password2" placeholder="确认密码">
                        </div>
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                            </div>
                            <div class="input-group-addon">
                                <span class="sms-captcha-btn">发送验证码</span>
                            </div>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" value="立即注册">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>