xfz/apps/payinfo/urls.py
from django.urls import path
from . import views

app_name = "payinfo"

urlpatterns = [
    path('', views.index, name='index'),
    path('payinfo_order/', views.payinfo_order, name='payinfo_order'),
    path('notify_url/', views.notify_view, name='notify_view'),
    path('download/', views.download, name='download')
]

xfz/xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', views.index, name='index'),
                  path('search/', include('haystack.urls')),
                  path('cms/', include('apps.cms.urls')),
                  path('account/', include("apps.xfzauth.urls")),
                  path('news/', include('apps.news.urls')),
                  path("course/", include("apps.course.urls")),
                  path("payinfo/", include("apps.payinfo.urls")),
                  path("ueditor/", include("apps.ueditor.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

xfz/apps/payinfo/models.py
from django.db import models
from shortuuidfield import ShortUUIDField
from django.core import validators
from django.conf import settings


class Payinfo(models.Model):
    title = models.CharField(max_length=100)
    profile = models.CharField(max_length=200)
    price = models.FloatField()
    path = models.FilePathField()


class PayinfoOrder(models.Model):
    uid = ShortUUIDField(primary_key=True)
    payinfo = models.ForeignKey("Payinfo", on_delete=models.DO_NOTHING)
    buyer = models.ForeignKey("xfzauth.User", on_delete=models.DO_NOTHING)
    amount = models.FloatField(default=0)
    pub_time = models.DateTimeField(auto_now_add=True)
    # 1：代表的是支付宝支付。2：代表的是微信支付
    istype = models.SmallIntegerField(default=0)
    # 1：代表的是未支付。2：代表的是支付成功
    status = models.SmallIntegerField(default=1)

xfz/apps/payinfo/views.py
# encoding: utf-8

from django.shortcuts import render
from .models import Payinfo, PayinfoOrder
from ..xfzauth.decorators import xfz_login_required
from django.views.decorators.csrf import csrf_exempt
from ..utils import restful
from django.shortcuts import reverse
from django.http import FileResponse, Http404
from django.conf import settings
import os


def index(request):
    context = {
        'payinfos': Payinfo.objects.all()
    }
    return render(request, 'payinfo/payinfo.html', context=context)


@xfz_login_required
def payinfo_order(request):
    payinfo_id = request.GET.get('payinfo_id')
    payinfo = Payinfo.objects.get(pk=payinfo_id)
    order = PayinfoOrder.objects.create(payinfo=payinfo, buyer=request.user, status=1, amount=payinfo.price)
    context = {
        'goods': {
            'thumbnail': '',
            'price': payinfo.price,
            'title': payinfo.title
        },
        'order': order,
        'notify_url': request.build_absolute_uri(reverse('payinfo:notify_view')),
        'return_url': request.build_absolute_uri(reverse('payinfo:index'))
    }
    return render(request, 'course/course_order.html', context=context)


@csrf_exempt
def notify_view(request):
    orderid = request.POST.get("orderid")
    PayinfoOrder.objects.filter(pk=orderid).update(status=2)
    return restful.ok()


@xfz_login_required
def download(request):
    payinfo_id = request.GET.get('payinfo_id')
    order = PayinfoOrder.objects.filter(payinfo_id=payinfo_id, buyer=request.user, status=2).first()
    if order:
        payinfo = order.payinfo
        path = payinfo.path
        # /a/xx.png = ['',a,xx.png]
        fp = open(os.path.join(settings.MEDIA_ROOT, path), 'rb')
        response = FileResponse(fp)
        # response['Content-Type'] = 'image/jpeg'
        response['Content-Type'] = 'application/pdf'
        response['Content-Disposition'] = 'attachment;filename="%s"' % path.split("/")[-1]
        return response
    else:
        return Http404()

xfz/front/templates/payinfo/payinfo - 副本.html
{% extends 'base/front_base.html' %}
{% load payinfo_filters %}

{% block title %}
    付费资讯
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/payinfo/payinfo.min.css' %}">
{% endblock %}

{% block main %}
    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="advertise-group">
                    <a href="#">
                        <img src="http://www.xfz.cn/static/build/images/web-venture-banner.png" alt="">
                    </a>
                </div>
                <ul class="document-list">
                    {% for payinfo in payinfos %}
                        <li>
                            {% with payinfo|is_buyed:user as buyed %}
                             {% if buyed %}
                                 <a href="{% url 'payinfo:download' %}?payinfo_id={{ payinfo.pk }}">
                             {% else %}
                                 <a href="{% url 'payinfo:payinfo_order' %}?payinfo_id={{ payinfo.pk }}">
                             {% endif %}

                                <div class="category-group" style="background-image:url('http://xfz.cn/static/build/images/web-bp-pc.png');"></div>
                                <div class="document-info">
                                    <p class="document-title">{{ payinfo.title }}</p>
                                    <p class="document-desc">{{ payinfo.profile }}</p>
                                    <p class="document-price">
                                        {% if buyed %}
                                            点击下载                                                                  {% else %}
                                            ￥{{ payinfo.price }}
                                        {% endif %}
                                    </p>
                                </div>
                            </a>
                        {% endwith %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}

xfz/front/templates/payinfo/payinfo.html
{% extends 'base/front_base.html' %}
{% load payinfo_filters %}

{% block title %}
付费资讯
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/payinfo/payinfo.min.css' %}">
{% endblock %}

{% block main %}
<div class="main">
    <div class="wrapper">
        <div class="main-content-wrapper">
            <div class="advertise-group">
                <a href="#">
                    <img src="http://www.xfz.cn/static/build/images/web-venture-banner.png" alt="">
                </a>
            </div>
            <ul class="document-list">
                {% for payinfo in payinfos %}
                <li>
                    {% with payinfo|is_buyed:user as buyed %}
                    {% if buyed %}
                    <a href="{% url 'payinfo:download' %}?payinfo_id={{ payinfo.pk }}">
                        {% else %}
                        <a href="{% url 'payinfo:payinfo_order' %}?payinfo_id={{ payinfo.pk }}">
                            {% endif %}

                            <div class="category-group" style="background-image:url('http://xfz.cn/static/build/images/web-bp-pc.png');"></div>
                            <div class="document-info">
                                <p class="document-title">{{ payinfo.title }}</p>
                                <p class="document-desc">{{ payinfo.profile }}</p>
                                <p class="document-price">
                                    {% if buyed %}
                                    点击下载
                                    {% else %}
                                    ￥{{ payinfo.price }}
                                    {% endif %}
                                </p>
                            </div>
                        </a>
                        {% endwith %}
                </li>
                {% endfor %}
            </ul>
        </div>
        {% include 'common/sidebar.html' %}
    </div>
</div>
{% endblock %}