xfz/apps/news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path('<int:news_id>/', views.news_detail, name="news_detail"),
    path('list/', views.news_list, name='news_list'),
    path('public_comment/', views.public_comment, name='public_comment')
]

xfz/xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', views.index, name='index'),
                  path('search/', include('haystack.urls')),
                  path('cms/', include('apps.cms.urls')),
                  path('account/', include("apps.xfzauth.urls")),
                  path('news/', include('apps.news.urls')),
                  path("course/", include("apps.course.urls")),
                  path("payinfo/", include("apps.payinfo.urls")),
                  path("ueditor/", include("apps.ueditor.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

xfz/apps/news/models.py
from django.db import models


class NewsCategory(models.Model):
    name = models.CharField(max_length=100)


class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('NewsCategory', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('xfzauth.User', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-pub_time']


class Comment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey("News", on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey("xfzauth.User", on_delete=models.CASCADE)

    class Meta:
        ordering = ['-pub_time']


class Banner(models.Model):
    priority = models.IntegerField(default=0)
    image_url = models.URLField()
    link_to = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-priority']

xfz/apps/news/forms.py
from django import forms
from apps.forms import FormMixin


class PublicCommentForm(forms.Form, FormMixin):
    content = forms.CharField()
    news_id = forms.IntegerField()

xfz/apps/news/views.py
from django.shortcuts import render
from .serializers import NewsSerializer, CommentSerizlizer
from .models import News, NewsCategory, Comment, Banner
from django.conf import settings
from ..utils import restful
from django.http import JsonResponse, HttpResponse
from django.http import Http404
from .forms import PublicCommentForm
from ..xfzauth.decorators import xfz_login_required
from django.db.models import Q


def index(request):
    # 默认展开2篇新闻
    count = settings.ONE_PAGE_NEWS_COUNT
    newses = News.objects.select_related('category', 'author').all()[0:count]
    categories = NewsCategory.objects.all()
    context = {
        'newses': newses,
        'categories': categories,
        'banners': Banner.objects.all(),
    }
    return render(request, 'news/index.html', context=context)


def news_list(request):
    # 通过p参数，来指定要获取第几页的数据
    # 并且这个p参数，是通过查询字符串的方式传过来的/news/list/?p=2
    page = int(request.GET.get('p', 1))
    # 分类为0：代表不进行任何分类，直接按照时间倒序排序
    category_id = int(request.GET.get('category_id', 0))
    # 0,1
    # 2,3
    # 4,5
    start = (page - 1) * settings.ONE_PAGE_NEWS_COUNT
    end = start + settings.ONE_PAGE_NEWS_COUNT

    if category_id == 0:
        # QuerySet
        # {'id':1,'title':'abc',category:{"id":1,'name':'热点'}}
        newses = News.objects.select_related('category', 'author').all()[start:end]
    else:
        newses = News.objects.select_related('category', 'author').filter(category__id=category_id)[start:end]
    serializer = NewsSerializer(newses, many=True)
    data = serializer.data
    return restful.result(data=data)


# 新闻详情页面
def news_detail(request, news_id):
    try:
        news = News.objects.select_related('category', 'author').prefetch_related("comments__author").get(pk=news_id)
        # news = News.objects.get(pk=news_id)
        context = {
            'news': news
        }
        return render(request, 'news/news_detail.html', context=context)
    except News.DoesNotExist:
        return HttpResponse("您找的页面不存在")


@xfz_login_required
def public_comment(request):
    form = PublicCommentForm(request.POST)
    if form.is_valid():
        news_id = form.cleaned_data.get('news_id')
        content = form.cleaned_data.get('content')
        news = News.objects.get(pk=news_id)
        comment = Comment.objects.create(content=content, news=news, author=request.user)
        serizlize = CommentSerizlizer(comment)
        return restful.result(data=serizlize.data)
    else:
        return restful.params_error(message=form.get_errors())


# 搜索页面
def search(request):
    q = request.GET.get('q')
    context = {}
    if q:
        newses = News.objects.filter(Q(title__icontains=q) | Q(content__icontains=q))
        num = News.objects.filter(Q(title__icontains=q) | Q(content__icontains=q)).count()
        print("==========================================")
        print(num)
        print(newses)
        print("==========================================")
        context['newses'] = newses
        context['num'] = num

    return render(request, 'search/search.html', context=context)

xfz/front/templates/news/index.html
{% extends 'base/front_base.html' %}

{% block title %}小饭桌{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/news/index.min.css' %}">
<script src="{% static 'js/index.min.js' %}"></script>
{% endblock %}

{% block main %}
<div class="main">
    <div class="wrapper">
        <div class="main-content-wrapper">
            <!--轮播图-->
            <div class="banner-group" id="banner-group">
                <ul class="banner-ul" id="banner-ul">
                    <li><a href="#"><img src="https://static-image.xfz.cn/1571105333_385.jpg"></a></li>
                    <li><a href="#"><img src="https://static-image.xfz.cn/1570765909_110.png"></a></li>
                    <li><a href="#"><img src="https://static-image.xfz.cn/1571292192_9.jpg"></a></li>
                    <li><a href="#"><img src="https://static-image.xfz.cn/1571191958_695.png"></a></li>
                    <li><a href="#"><img src="https://static-image.xfz.cn/1571885973_544.jpg"></a></li>
                </ul>
                <!--尖括号 左右箭头-->
                <span class="arrow left-arrow">‹</span>
                <span class="arrow right-arrow">›</span>
                <!--小圆点-->
                <div class="page-control-group">
                    <ul class="page-control">
                        <!--js会动态生成小点点-->
                        <!--<li class="active"></li>-->
                        <!--<li></li>-->
                        <!--<li></li>-->
                        <!--<li></li>-->
                    </ul>
                </div>
            </div>
            <div class="list-outer-group">
                <ul class="list-tab">
                    <li class="active"><a href="#">最新资讯</a></li>
                    <li><a href="#">热点</a></li>
                    <li><a href="#">深度报道</a></li>
                    <li><a href="#">干货分享</a></li>
                    <li><a href="#">投资人说</a></li>
                </ul>
                <ul class="list-inner-group">
                    <li>
                        <div class="thumbnail-group">
                            <a href="#">
                                <img src="https://static-image.xfz.cn/1578101299_163.jpg-website.news.list" alt="">
                            </a>
                        </div>
                        <div class="news-group">
                            <p class="title">
                                <a href="#"> 早报：OYO被曝房源造假；理想汽车秘密申请美国IPO；滴滴出行暂停新司机注册审核7天</a>
                            </p>
                            <p class="desc">
                                滴滴顺风车1月6日上线杭州、上海等8个城市试运营
                            </p>
                            <p class="more">
                                <span class="category">深度报道</span>
                                <span class="pub-time">1小时前</span>
                                <span class="author">知了课堂</span>
                            </p>
                        </div>
                    </li>

                    <li>
                        <div class="thumbnail-group">
                            <a href="#">
                                <img src="https://static-image.xfz.cn/1577945078_284.png-website.news.list" alt="">
                            </a>
                        </div>
                        <div class="news-group">
                            <p class="title">
                                <a href="#"> 打造开店人“小红书”， 店鹿获450万天使融资</a>
                            </p>
                            <p class="desc">
                                投资方为亮马资本
                            </p>
                            <p class="more">
                                <span class="category">热点</span>
                                <span class="pub-time">2小时前</span>
                                <span class="author">知了课堂</span>
                            </p>
                        </div>
                    </li>



                </ul>
                <div class="load-more-group">
                    <button class="load-more">查看更多</button>
                </div>
            </div>

        </div>
        {% include 'common/sidebar.html' %}
    </div>
</div>
{% endblock %}

xfz/front/templates/news/index1.html
{% extends 'base/front_base.html' %}
{% load news_filters %}

{% block title %}
小饭桌
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/news/index.min.css' %}">
<script src="{% static 'arttemplate/template-web.js' %}"></script>
<script src="{% static 'js/index.min.js' %}"></script>
<script id="news-item" type="text/html">
    {% verbatim %}
    {{ each newses news index }}
    <li>
        <div class="thumbnail-group">
            <a href="/news/{{ news.id }}/">
                <img src="{{ news.thumbnail }}" alt="">
            </a>
        </div>
        <div class="news-group">
            <p class="title">
                <a href="/news/{{ news.id }}/">{{ news.title }}</a>
            </p>
            <p class="desc">
                {{ news.desc }}
            </p>
            <p class="more">
                <span class="category">{{ news.category.name }}</span>
                <span class="pub-time">{{ news.pub_time|timeSince }}</span>
                <span class="author">{{ news.author.username }}</span>
            </p>
        </div>
    </li>
    {{ /each }}
    {% endverbatim %}
</script>
{% endblock %}

{% block main %}
<div class="main">
    <div class="wrapper">
        <div class="main-content-wrapper">
            <div class="banner-group" id="banner-group">
                <ul class="banner-ul" id="banner-ul">
                    {% for banner in banners %}
                    <li>
                        <a href="{{ banner.link_to }}">
                            <img src="{{ banner.image_url }}" alt="">
                        </a>
                    </li>
                    {% endfor %}
                </ul>
                <span class="arrow left-arrow">‹</span>
                <span class="arrow right-arrow">›</span>
                <div class="page-control-group">
                    <ul class="page-control">
                    </ul>
                </div>
            </div>
            <div class="list-outer-group">
                <ul class="list-tab">
                    <li data-category="0" class="active"><a href="javascript:void(0);">最新资讯</a></li>
                    {% for category in categories %}
                    <li data-category="{{ category.pk }}"><a href="javascript:void(0);">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
                <ul class="list-inner-group">
                    {% for news in newses %}
                    <li>
                        <div class="thumbnail-group">
                            <a href="{% url 'news:news_detail' news_id=news.pk %}">
                                <img src="{{ news.thumbnail }}" alt="">
                            </a>
                        </div>
                        <div class="news-group">
                            <p class="title">
                                <a href="{% url 'news:news_detail' news_id=news.pk %}">{{ news.title }}</a>
                            </p>
                            <p class="desc">
                                {{ news.desc }}
                            </p>
                            <p class="more">
                                <span class="category">{{ news.category.name }}</span>
                                <span class="pub-time">{{ news.pub_time|time_since }}</span>
                                <span class="author">{{ news.author.username }}</span>
                            </p>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
                <div class="load-more-group">
                    <button class="load-more" id="load-more-btn">查看更多</button>
                </div>
            </div>
        </div>
        {% include 'common/sidebar.html' %}
    </div>
</div>
{% endblock %}

xfz/front/templates/news/news_detail.html
{% extends 'base/front_base.html' %}
{% load news_filters %}

{% block title %}
    新闻详情页
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/news/news_detail.min.css' %}">
<script src="{% static 'arttemplate/template-web.js' %}"></script>
<script src="{% static 'js/news_detail.min.js' %}"></script>
<script id="comment-item" type="text/html">
    {% verbatim %}
    <li>
        <div class="comment-info">
            <img src="http://q5jl6xwjh.bkt.clouddn.com/1581514332894.png" alt="" class="avatar">
            <span class="author">{{ comment.author.username }}</span>
            <span class="pub-time">{{ comment.pub_time|timeSince }}</span>
        </div>
        <p class="comment-content">{{ comment.content }}</p>
    </li>
    {% endverbatim %}
</script>
{% endblock %}

{% block main %}
<div class="main">
    <div class="wrapper">
        <div class="main-content-wrapper">
            <div class="news-wrapper">
                <h1 class="title">{{ news.title }}</h1>
                <div class="news-info">
                    <div class="info-group">
                        <span class="author">{{ news.author.username }}</span>
                        <span class="pub-time">{{ news.pub_time|time_since }}</span>
                        <span class="category">{{ news.category.name }}</span>
                    </div>
                    <div class="share-group">
                        <span>分享至：</span>
                        <a class="weixin share-item"></a>
                        <a href="#" class="weibo share-item"></a>
                    </div>
                </div>
                <article class="article">
                    {{ news.content|safe }}
                </article>
            </div>
            <div class="comment-wrapper">
                <h3 class="title">文章评论（0）</h3>
                <textarea name="comment" class="comment-textarea logined-textarea" placeholder="立即登录，参与评论~"></textarea>
                <div class="submit-btn-group">
                    <button class="submit-btn" data-news-id="{{ news.pk }}">立即评论</button>
                </div>
                <ul class="comment-list">
                    {% for comment in news.comments.all %}
                    <li>
                        <div class="comment-info">
                            <img src="http://q5jl6xwjh.bkt.clouddn.com/1581514332894.png" alt="" class="avatar">
                            <span class="author">{{ comment.author.username }}</span>
                            <span class="pub-time">{{ comment.pub_time|time_since }}</span>
                        </div>
                        <p class="comment-content">{{ comment.content }}</p>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% include 'common/sidebar.html' %}
    </div>
</div>
{% endblock %}